#!/usr/bin/env python

import os
import sys
import logging
import subprocess

tag_name = sys.argv[1]
upload_url = sys.argv[2]
repository_name = sys.argv[3]
repository_url = sys.argv[4]
github_token = sys.argv[5]

repository_url_token = repository_url.replace('github', github_token+"@"+"github", 1)

subprocess.call(["mkdir", "-p", tag_name+"/out"])

logging.basicConfig(filename=tag_name+'/out/build.log', level=logging.DEBUG)
logging.info("build pending ...")

header = "Content-Type:application/zip"

try:
    out_clone = subprocess.check_output(["git", "clone", "-b", tag_name, "--depth", "1", repository_url_token], cwd=tag_name)
    
    out_build = subprocess.check_output(["make", "cd"], cwd=tag_name+"/"+repository_name)
    
    logging.info(out_build)

except subprocess.CalledProcessError as e:
    logging.error(e.output)

out_zip = subprocess.check_output(["zip", "-r", "build-results.zip", "out"], cwd=tag_name)

out_upload = subprocess.check_output(["curl", "-XPOST", "-H", header, "--data-binary", "@build-results.zip", upload_url+"?access_token="+github_token+"&name=build-results.zip"], cwd=tag_name)

subprocess.call(["rm", "-rf", tag_name])
