#!/usr/bin/env python3

import os
import sys
import subprocess

tag_name = sys.argv[1]
upload_url = sys.argv[2]
repository_name = sys.argv[3]
repository_url = sys.argv[4]
github_token = sys.argv[5]

def logging(log):
    with open(tag_name+'/out/build.log', 'a') as f:
        f.write(log.decode("utf-8") + '\n')

if not os.path.isdir(tag_name+"/out"):
    subprocess.call(["mkdir", "-p", tag_name+"/out"])
else:
    sys.exit()

repository_url_token = repository_url.replace('github', github_token+"@"+"github", 1)

logging(b'build pending ...')

header = "Content-Type:application/zip"

out_clone = subprocess.check_output(["git", "clone", "-b", tag_name, "--depth", "1", repository_url_token], cwd=tag_name)

logging(out_clone)

out_build = subprocess.check_output(["make", "cd"], cwd=tag_name+"/"+repository_name)
    
logging(out_build)

out_zip = subprocess.check_output(["zip", "-r", "build-results.zip", "out"], cwd=tag_name)

logging(out_zip)

out_upload = subprocess.check_output(["curl", "-XPOST", "-H", header, "--data-binary", "@build-results.zip", upload_url+"?access_token="+github_token+"&name=build-results.zip"], cwd=tag_name)

logging(out_upload)

subprocess.call(["rm", "-rf", tag_name])
